### ISSUE TITLE
Application Window moves to primary monitor when clicking ribbon icon to activate/focus

### ISSUE THREAD

**Issue by rene-aguirre** [SQLiteFlow/SQLiteFlow-Issues#189] opened 2022-03-23 19:02 UTC
**Version**
 - Platform: macOS 12.x
 - SQLiteFlow: 5.6.3

**Steps to Reproduce**
1) Open SQLiteFlow, move to secondary monitor, work as usual (e.g. open a file, do some filters)
2) Keep SQLiteFlow in normal view, click other other application window in secondary monitor (e.g. move to browser)
3) At this point SQLiteFlow window is still in secondary monitor but hidden by other App window that'd be focused, possibly not visible
4) Click the SQLiteFlow icon in the ribbon to switch/activate the hidden window, it shouldn't matter if you click the ribbon in the primary monitor or secondary

**Expected behavior**
SQLiteFlow main window should move to the top in the current monitor: secondary window

**Actual behavior**
SQLiteFlow window always restores to the primary monitor so you need to drag it back to the secondary monitor to keep working

**Comment by rene-aguirre** [comment] 2022-03-23 19:19
This issue is not 100% reproducible, I don't know what'd be the trigger (maybe different sequences minimizing the app then click the ribbon icon to restore)

**Comment by SQLiteFlow** [comment] 2022-03-24 01:43
Simplified reproduce steps:
1. Open SQLiteFlow, move to secondary monitor, press CMD+H to hide the app.
2. Click the SQLiteFlow icon in the ribbon to switch/activate the hidden window.

Expected behavior
SQLiteFlow main window should move to the top in the current monitor: secondary window

Actual behavior
SQLiteFlow window always restores to the primary monitor so you need to drag it back to the secondary monitor to keep working


This bug caused by fixing the first issue metioned in https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/144.
And looks like it's not an issue anymore when build the app with the latest Xcode (13.3) even if comment out the fix.

So I will release a new version soon to fix the current issue.

**Comment by SQLiteFlow** [comment] 2022-03-24 09:35
This issue should be fixed in the latest version of SQLiteFlow(macOS) (5.6.6), and it's available on App Store now.

**Closed** 2022-03-26 01:59 UTC
