### ISSUE TITLE
App crashed on Big Sur and deleted every SQL file it had open!

### ISSUE THREAD

**Issue by drekka** [SQLiteFlow/SQLiteFlow-Issues#154] opened 2020-11-30 05:45 UTC
**Version**
 - Platform: 11.1 Beta (20C5048k)
 - SQLiteFlow: 4.7.0

**Steps to Reproduce**
1. Open an SQL file
2. Edit it and run it. 

**Expected behavior**
App runs SQL every time and does not crash.

**Screen shots**
App crashed after running the file several times. No clear reason why. HOWEVER when I restarted it, I found that all the SQL files I had open when it crashed had been deleted.

This is a serious error. An app crash should not delete any files. At worst, it can forget whatever it's got in memory that hasn't been saved, but it should never cause files to be removed.

**Comment by SQLiteFlow** [comment] 2020-11-30 05:56
When you say "Open an SQL file", can I get the steps that how you open it?
And where is the SQL file stored? Like Desktop folder, Download folder, iCloud folder or USB disk?

**Comment by drekka** [comment] 2020-12-01 10:37
I just opened a SQL file I've stored in an app's development directories. So it can come from anywhere. 

The other thing that's got me baffled is how to get an SQL to run against a specific database. I have several open as I'm working on some scripts to migrate some data from an old app so I really need to be able to create an SQL file, then run I against a specific database.

**Comment by drekka** [comment] 2020-12-01 10:46
Hmmm. My script title has ... (Mem) next to it which I think means it's not associated with any database. I've been all over the UI and menus and I can see how to specify which database it should run on. I found that closing it, selecting a database, then re-opening it associates it, but I really need something a bit simpler than that. A menu option or popup, or button at the top of the editor where I can select the database would be good.

**Comment by SQLiteFlow** [comment] 2020-12-01 11:18
> I just opened a SQL file I've stored in an app's development directories.

I re-checked the code, I don't think there's any logic in SQLiteFlow to delete an already saved (that is not new created and not saved yet) SQL file, whatever it crash or not. 
So could you reproduce the issue now? I think you can simulate a crash through  - > Force Quit...

> I've been all over the UI and menus and I can see how to specify which database it should run on.

When you open or create a SQL file, the file will be automatically associated with the selected database in database list. In the window's title, it will show the name of the database associated.
If there's no database selected, then the file will be associated with a SQLite memory database, and that's the "Mem" in the title short for.

> I found that closing it, selecting a database, then re-opening it associates it, but I really need something a bit simpler than that. A menu option or popup, or button at the top of the editor where I can select the database would be good.

You are right, currently changing the SQL file associated database is not supported yet, but I'm interest to implement it.
And currently a workaround to make it easier is open a database first, then open a SQL file.

**Comment by SQLiteFlow** [comment] 2020-12-10 10:25
This issue has been reproduced.
It caused by the app handle edited file incorrectly after crash.

The app moved the files to the location below after crash, which should not. The location below suppose to store about top 15 "Recent Temp Queries".

**So maybe you can retrieve your missing queries here:**
`~/Library/Containers/com.hyperobjc.SQLiteFlow-macOS/Data/Documents/QuerySessions/
`

I will release a fix as soon as possible.
And thank you for the report.

**Comment by SQLiteFlow** [comment] 2020-12-12 00:14
Fixed in SQLiteFlow(macOS) 4.8.0. 
This version is available on App Store now.

**Closed** 2020-12-12 20:29 UTC
Labels: bug, released

**Comment by drekka** [comment] 2020-12-15 03:21
Thanks. Yes I managed to find the SQLs so I was ok again.
