### ISSUE TITLE
[macOS] Issue with SQLiteFlow ignoring foreign key RESTRICT

### ISSUE THREAD

**Issue by JorgePadron** [SQLiteFlow/SQLiteFlow-Issues#95] opened 2020-04-18 03:01 UTC
**Version**
 - Platform: [e.g. macOS 10.14.5]
 - SQLiteFlow: [e.g. 3.6.0]

**Steps to Reproduce**
1. With PRAGMA fereign_keys = OK, my Foreign Keys RESTRICK is being ignored on the SQLiteFlow App, whereas the same Foreign Keys RESTRICK is working OK on the DB Browser App.

2. Additionally, in a Query Window, individually running...
PRAGMA foreign_keys = ON;
...to turn ON foreign keys support and then individually running...
PRAGMA foreign_keys;
...to confirm foreign keys status, it returns "0", which is wrong. It should return "1".

Please advise. Thanks.

**Expected behavior**

**Screen shots**

**Comment by SQLiteFlow** [comment] 2020-04-18 03:23
Hello @JorgePadron,
To make foreign key constraints work, from the official [SQLite documentation](https://sqlite.org/foreignkeys.html)
> It must still be enabled by the application at runtime, using the PRAGMA foreign_keys command. For example: `PRAGMA foreign_keys = ON;`

So, after you execute `PRAGMA foreign_keys = ON`, the result of `PRAGMA foreign_keys;` will should be 1 in that database connection.

So to test foreign key constraints in Query Editor, you can add `PRAGMA foreign_keys = ON;` before other queries. Like
```
PRAGMA foreign_keys = ON;
... INSERT/UPDATE values...;
```

And to test foreign key constraints in Data Editor, there's an option in UI that can let user enable it in runtime, a screen shot of it has been attached.

![Screen Shot](https://user-images.githubusercontent.com/38027540/66195194-af46a100-e6c8-11e9-9568-69e39824bda8.png)

**Comment by JorgePadron** [comment] 2020-04-18 04:38
Thank you for your quick reply. I understand everything you mentioned on your reply. However, my point is that even after enabling PRAGMA foreign_keys support, SQLiteFlow still returns '0' when I run PRAGMA foreign_keys; on the Query Window editor, which is wrong, whereas on sqlite3 and on DB Browser, I get the the correct value '1', as seen on the attached screenshots. 

Running PRAGMA foreign_keys; on the SQLiteFlow query window editor should return '1' (not '0') if foreign keys support was previously enabled, like it does on sqlite3 and DB Browser.


![Screen Shot 2020-04-18 at 12 16 22 AM](https://user-images.githubusercontent.com/633087/79628184-c6049080-810c-11ea-90bc-adae72c470fb.png)

![Screen Shot 2020-04-18 at 12 15 07 AM](https://user-images.githubusercontent.com/633087/79628187-ca30ae00-810c-11ea-9430-b6843f78454e.png)

**Comment by SQLiteFlow** [comment] 2020-04-18 08:09
@JorgePadron Thank you for the reply, and I think I get your point. 

Please let me explain why SQLiteFlow behaves like that. And generally speaking, it's a feature.

From the SQLite document I mentioned before:
> Foreign key constraints are disabled by default (for backwards compatibility), so must be **enabled separately for each database connection**.

After SQLiteFlow opened a SQLite file, a new database connection will be created whenever SQLiteFlow needs to read or write the database, and after the reading or writing finished, the connection then will be released.

So you can see that unlike sqlite3 shell or some other apps, there's no such a thing that so called the global database connection in SQLiteFlow. In SQLiteFlow, database connection will only be created when it's needed and be released when it's not needed.

In particular, every time when you click 'Refresh' button in Data Editor, or when you click 'Run' button in Query Editor, a new database connection will be created for doing its own job and be released when its job has been done.

So in Data Editor, if 'Enable foreign key constraints' set to 'On', SQLiteFlow will automatically insert `PRAGMA foreign_keys = ON;` at the beginning of queries that are going to be executed in this tab.

In Query Editor, SQLiteFlow will NOT change anything to the queries that are going to be executed, so it will not insert something like `PRAGMA foreign_keys = ON;` automatically of course.

SQLiteFlow intent to be user's good friend as a developer tool, like when user click 'Run' button in Query Editor, user is confident that the queries will be executed in a clean state, not mess up with many kind of settings like PRAGMA foreign_keys, PRAGMA busy_timeout etc that user may not aware where set it.

**Comment by JorgePadron** [comment] 2020-04-18 13:59
Thanks again for your quick reply. Even SQLite recognizes the issue and so they allow users to mitigate this shortcoming by allowing users to enable foreign keys by default on the sqlite3 shell by adding the PRAGMA to the user's home directory .sqliterc file, as seen on the attached sqliterc screenshot. 

By allowing this workaround, sqlite3 mitigates and alleviates the default foreign keys OFF issue, so every time we start sqlite3, foreign keys are always "ON" and kept "ON" at all times, as seen on the attached foreign_keys ON screenshot.

I believe it is unfortunate that while other SQLite IDE Apps, including SQLite's own sqlite3 shell App, have been able to mitigate the foreign keys being disabled by default, you guys have instead decided to make this SQLite shortcoming a SQLiteFlow design feature.


![sqliterc](https://user-images.githubusercontent.com/633087/79639631-f5da8500-815a-11ea-82f4-44e428b966c6.png)

![foreign_keys ON](https://user-images.githubusercontent.com/633087/79639637-fbd06600-815a-11ea-92a6-f2fdcb157c07.png)

**Comment by SQLiteFlow** [comment] 2020-04-18 14:58
@JorgePadron I mean it's a design feature that there's no global database connection. But it's side effect which seems bring a little inconvenience to you isn't a feature, it's definitely a subject to enhancement. 😄
What do you think if we can also add an option in UI to Query Editor which could let user enable foreign key constraint in runtime(that is when user click the 'Run' button)? The option is similar to what it is in Data Editor.

**Comment by JorgePadron** [comment] 2020-04-18 16:01
Adding an option in the UI Query Editor to let the user enable the foreign key constraint in runtime, exactly similar to the one in the Data Editor would certainly be a step in the right direction. 

But what would in my opinion be a better solution would be to make the following two enhancements:

1. Add the "Enable foreign keys constraints:" Default/On/Off pull-down menu to the SQLiteFlow App Preferences' General page (see attachment), (obviously) using the properly Mac UI capitalized words "Enable Foreign Key Constraints:". That way, users can decide themselves to permanently use either SQLite's Default Foreign Key Constraints setting, or set it permanently to always be On or Off.

2. Remove the existing "Enable foreign keys constraints:" Default/On/Off pull-down menu from the Data Editor UI.

This would be my recommendation, as a SQL professional and a retired UI developer for 20 years.





![Enable foreign keys on the App Preferences' General page](https://user-images.githubusercontent.com/633087/79641976-d9dde000-8168-11ea-8de4-a6623bd19220.png)

**Comment by SQLiteFlow** [comment] 2020-04-19 01:27
@JorgePadron Thank you for the suggestion.

After some thinking, I think your suggestion is better than mine and you convinced me.

This setting will have effect on Data Editor, Query Editor and Import CSV, and probably any future feature that may make changes to the content of the database.

Since this feature will bring user convenience, so why not bring it to the world, and yes, I will implement it in future version.😀

**Comment by SQLiteFlow** [comment] 2020-05-14 12:07
Finished.
Move the setting 'Enable Foreign Key Constraints' from Data Editor to Preference - General.
Now this setting will affect to Data Editor, Query Editor and Import CSV.

Screenshot attached.
![pic](https://user-images.githubusercontent.com/38027540/81932485-7a1b0d80-961e-11ea-8290-61ad83993691.png)

**Comment by SQLiteFlow** [comment] 2020-05-23 00:32
SQLiteFlow(macOS) 4.0.0 has been released.

**Comment by JorgePadron** [comment] 2020-05-23 15:39
Thank you for the version 4.0 update. It looks very good!

I have a question regarding the new relocated app _Preferences > General_ tab option "Enable Foreign Keys Constraints". I notice that, by default, its value is "Default". Does this mean that, by default, the PRAGMA foreign_keys value is OFF? 

I am asking because I changed this setting to ON and when I ran "PRAGMA foreign_keys;" in the Query Editor, it returned the correct value "1", meaning "ON". However, if I completely quit SQLiteFlow 4.0 and restart it, the app _Preferences > Gereral_ tab "Enable Foreign Key Constraints" shows "Default", not the "ON" value I selected in my previous session. It seems like the App is not "remembering" this setting and so it goes back to "Default". Interestingly, even with the "Enable Foreign Key Constraints" setting is now showing "Default", if I run "PRAGMA foreign_keys" in the Query Editor, I still get "1", meaning "ON", even though the _Preferences > General_ tab setting says "Default". Hence my question, does your "Default" setting mean the PRAGMA foreign_keys value is ON or OFF?

Please advise.

![Screen Shot 2020-05-23 at 11 20 27 AM](https://user-images.githubusercontent.com/633087/82734478-3d6ba800-9ce9-11ea-8ad3-c5c00ffb7676.png)

![Screen Shot 2020-05-23 at 11 31 07 AM](https://user-images.githubusercontent.com/633087/82734482-42c8f280-9ce9-11ea-8e6f-cca6269a1004.png)

**Comment by JorgePadron** [comment] 2020-05-23 18:28
Follow up to my previous comment regarding version 4.0

The App Preferences > Text Editing "Tab Key Behavior" field also forgets its value.

1. From the SQLiteFlow menu, open Preferences > Text Editing and select "Inserts Spaces" in the "Tab Key Behavior" field.
2. Close the dialog box, quit SQLiteFlow.
3. Open SQLiteFlow, open Preferences > Text Editing. The "Tab Key Behavior" field shows "Inserts Tab Character" instead of "Inserts Spaces".

**Comment by SQLiteFlow** [comment] 2020-05-23 22:07
The two issues are reproduced. 
They are display issue in Preference, will release a fix as soon as possible.

**Comment by SQLiteFlow** [comment] 2020-05-25 01:44
SQLiteFlow(macOS) 4.0.1 has been released.
Sorry for the bug and the confusion it made.

And the value "Default" means SQLiteFlow do nothing about the `PRAGMA foreign_keys`, and since currently the SQLite library let the default value of `PRAGMA foreign_keys` is `0`, so yes, currently the "Default" means OFF.
The value "On" means execute the SQL `PRAGMA foreign_keys = on;` before execute any SQL.
The value "Off" means execute the SQL `PRAGMA foreign_keys = off;` before execute any SQL.

The three screenshots below show the difference of the three options "Default", "On", "Off" in Query Editor.
![Default](https://user-images.githubusercontent.com/38027540/82770592-aed36400-9e6b-11ea-897b-ca1f1bdce1d5.png)
![On](https://user-images.githubusercontent.com/38027540/82770600-b430ae80-9e6b-11ea-912c-dc08a7912bda.png)
![Off](https://user-images.githubusercontent.com/38027540/82770601-b4c94500-9e6b-11ea-98c6-5250747f1ad2.png)

**Comment by JorgePadron** [comment] 2020-05-25 02:52
Thank you for you quick 4.0.1 release. Awesome job!

THANK YOU!

**Comment by SQLiteFlow** [comment] 2020-05-25 03:05
You are welcome! And thank you too!

**Closed** 2020-05-25 03:06 UTC
Labels: enhancement, released
