### ISSUE TITLE
Excuse me, my mac pro 16 with Catalina 10.15.6 has some problems with this app. It always flashes and shrinks to a small black interface, and it's not very fluent when I tried to switch to the full-screen mode. The flashing problem really drives me craze, I hope that's not my mac's problem. Any idea or improvement? Thanks much!

### ISSUE THREAD

**Issue by junlin1998** [SQLiteFlow/SQLiteFlow-Issues#144] opened 2020-09-15 04:55 UTC

**Comment by SQLiteFlow** [comment] 2020-09-15 05:38
Can I have a video about the issue?

**Comment by junlin1998** [comment] 2020-09-15 05:58
Sure, please see the attached.


| |
林峻Jack
|
|
18516390686@163.com
|
签名由网易邮箱大师定制


On 09/15/2020 13:39，SQLiteFlow<notifications@github.com> wrote：

Can I have a video about the issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

从网易邮箱大师发来的云附件
Screen Recording 2020-09-15 at 1.56.16 PM.mov(90.7MB,2020年9月30日 13:58 到期)
下载

**Comment by SQLiteFlow** [comment] 2020-09-15 06:12
You may need attach your video file through Github website (that is not through e-mail), or I can't see the attached file.

Best regards.

**Comment by junlin1998** [comment] 2020-09-15 10:25
Ah….Idk how to upload video at Github….Any better idea?


| |
林峻Jack
|
|
18516390686@163.com
|
签名由网易邮箱大师定制


On 09/15/2020 14:12，SQLiteFlow<notifications@github.com> wrote：

You may need attach your video file through Github website (that is not through e-mail), or I can't see the attached file.

Best regards.

**Comment by SQLiteFlow** [comment] 2020-09-15 10:42
To upload your xxx.mov file through GitHub, the steps are:
1. Pack the `xxx.mov` file to `xxx.zip` file 
2. Then drag and drop your `xxx.zip` file to the comment text box.
3. Click "Comment", that's it!

**Comment by junlin1998** [comment] 2020-09-15 10:50
Emmm…. That’s good to know! But the file is too big to upload.
Anyways, I upload it onto Youtube
https://www.youtube.com/watch?v=qFUAHZZLbvc




| |
林峻Jack
|
|
18516390686@163.com
|
签名由网易邮箱大师定制


On 09/15/2020 18:42，SQLiteFlow<notifications@github.com> wrote：

To upload your xxx.mov file through GitHub, the steps are:

Pack the xxx.mov file to xxx.zip file
Then drag and drop your xxx.zip file to the comment text box.
Click "Comment", that's it!

**Comment by SQLiteFlow** [comment] 2020-09-15 11:21
Thank you!

I saw the video, and the issue has been reproduced. It happens when switch to full screen mode.
I will investigate it and release a fix as soon as I can.

Before this, if you prefer the app scale to full screen, a workaround is use Menu - Window - Zoom to make it kind of full screen, but with the Menu Bar unhidden.

**Comment by SQLiteFlow** [comment] 2020-09-15 13:03
Fixed.

**Comment by SQLiteFlow** [comment] 2020-09-15 14:10
The fix has been committed to review, the next version 4.6.1 will be available soon.

And in addition, I noticed that in your video, some table like "individual_xxxxx_with_ref..." has a very slow loading experience, and I think it probably caused by SQLiteFlow(macOS) not handle it very well when there're a lot of columns in a table.
And that's something that I think I can make improvement, so can I know the approximate column count in that table? I would like to have a sense of the destination of the potential improvement.

**Comment by junlin1998** [comment] 2020-09-15 14:16
Sure, the col num is abt 240 with 5475 rows. 
And thanks so much for the quick improvements!
I’d say if it can load dbs better, definitely the best Sqlite app in Mac!  


Thx so much!
| |
林峻Jack
|
|
邮箱：18516390686@163.com
|

签名由 网易邮箱大师 定制

On 09/15/2020 22:10, SQLiteFlow wrote:

The fix has been committed to review, the next version 4.6.1 will be available soon.

And in addition, I noticed that in your video, some table like "individual_xxxxx_with_ref..." has a very slow loading experience, and I think it probably caused by SQLiteFlow(macOS) not handle it very well when there're a lot of columns in a table.
And that's something that I think I can make improvement, so can I know the approximate column count in that table? I would like to have a sense of the destination of the potential improvement.

**Comment by SQLiteFlow** [comment] 2020-09-15 14:25
You're welcome.
And thank you too, I will see what I can do.

**Comment by SQLiteFlow** [comment] 2020-09-15 23:38
SQLiteFlow(macOS) 4.6.1 is available on App Store now.

**Closed** 2020-09-16 06:23 UTC
Labels: bug, released

**Comment by SQLiteFlow** [comment] 2020-11-05 02:20
The loading experience in Data Editor and Query Results has been improved.
Relative issue is https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/147.

The improved version 4.7.0 is available on App Store now.
