### ISSUE TITLE
Does the Unlimited Annual license work on iPad?

### ISSUE THREAD

**Issue by johnhopson** [SQLiteFlow/SQLiteFlow-Issues#238] opened 2024-08-03 17:31 UTC
I purchased the Unlimited Annual subscription on my Mac.  The license isn't found when I try to "Restore Previous Purchase" on the iPad version.  Am I doing something wrong?  Both the Mac and iPad are running the latest OS.  Both are running the latest SQLiteFlow too.

**Comment by SQLiteFlow** [comment] 2024-08-03 22:01
Thank you for using SQLiteFlow, you're doing nothing wrong, this is because the purchase of SQLitFlow(macOS) and SQLiteFlow(iOS) are separate, they're not shared.

**Comment by Founderstowne** [comment] 2024-08-17 23:30
Over the last month or so, I'm being asked to restore my purchase when logging in, too. When I try to log in, it fails. But when  I relaunch the software, it says I have a paid-in-full lifetime license.

**Comment by SQLiteFlow** [comment] 2024-08-17 23:43
@Founderstowne I believe what you're mentioning is belong to a different issue.
Does the app works normal after you finally see you have a lifetime license?
What platform are you using by the way? iOS or macOS?

**Comment by Founderstowne** [comment] 2024-08-18 02:06
Yes, the app works normal after. I'm not sure how long it stays logged in... it seems like it's a few weeks, then I'm asked again to login. I'm using macOS.

**Comment by SQLiteFlow** [comment] 2024-08-18 02:34
@Founderstowne I actually experienced the same issue months ago. When this issue happens, even restart the computer wouldn't fix the issue. 
Then I noticed that when this issue happened, I can't download any App from the Mac App Store either, but my network is fine (like I can open any website normally).
I way I fix this issue is restarting my network devices, after my network devices relaunches, then I try to re-open SQLiteFlow or download any App from the Mac App Store, everything then works fine (and I have no idea why this happens).
So if you experience this issue again, you can do a test by trying to download a App from the Mac App Store, if you can't download one, my guess is this is probably a glitch of Apple's server or a network issue. If you can download one, then this will probably be another story.

**Comment by Founderstowne** [comment] 2024-08-21 03:00
<img width="628" alt="SCR-20240820-tumr" src="https://github.com/user-attachments/assets/f81cc5fc-f769-4ac3-bb9d-36e638040838">

This happened again. See how I have a lifetime license, but I get this popup? And when I try to restore with my username and password, I get a logging error. I can't click the Lifetime License button... it's greyed (blued) out.

**Comment by SQLiteFlow** [comment] 2024-08-21 04:11
> Over the last month or so, I'm being asked to restore my purchase when logging in, too.

When this happens, what's the popup dialog displays? Lifetime license or no purchases?

> This happened again. See how I have a lifetime license, but I get this popup?

> I relaunch the software, it says I have a paid-in-full lifetime license.

What the popup displays on the screenshot attached is when after you relaunch the app, right?

> And when I try to restore with my username and password, I get a logging error. 

Actually when you do this, the app already transfer the control to the macOS. The logging error is thrown by macOS.
So does you Mac App Store can download apps normally when this happens?

> I can't click the Lifetime License button... it's greyed (blued) out

That's an expected behavior. Because when you have a Lifetime License, this button is useless anyway.

<br/>
Additional info:

SQLiteFlow uses [StoreKit 2](https://developer.apple.com/storekit/) to invalidate in-app purchases, when the app launches ,if the StoreKit framework report an invalidate in-app purchase error to the app, then the Purchase Plan dialog will popup (probably displaying with no purchases), and when the Purchase Plan dialog displaying, the app will call the StoreKit to refresh the in-app purchase state (maybe this is why you after relaunching the app, everything goes right).

And I still have no clue yet that why sometime when you launch the app, the StoreKit framework report an invalidate error to the app, this should happen very rare. And
What's your Mac device type?
What's your macOS version?
What's SQLiteFlow version?

**Comment by Founderstowne** [comment] 2024-08-21 12:54
> > Over the last month or so, I'm being asked to restore my purchase when logging in, too.
> 
> When this happens, what's the popup dialog displays? Lifetime license or no purchases?
Lifetime license... you can see it in the screenshot I posted above
> 
> > This happened again. See how I have a lifetime license, but I get this popup?
> 
> > I relaunch the software, it says I have a paid-in-full lifetime license.
> 
> What the popup displays on the screenshot attached is when after you relaunch the app, right?
I use Fetch FTP to log into my DigitalOcean droplet. I right-click on the SQLite.db and "Open with" using SQLiteFlow. That's when I get the popup. When I click out of the popup, your software works as expected.
> 
> > And when I try to restore with my username and password, I get a logging error.
> 
> Actually when you do this, the app already transfer the control to the macOS. The logging error is thrown by macOS. So does you Mac App Store can download apps normally when this happens?
Yes. In fact, I was able to download your updated software last night.
> 
> > I can't click the Lifetime License button... it's greyed (blued) out
> 
> That's an expected behavior. Because when you have a Lifetime License, this button is useless anyway.
From a UX perspective, I'd hide the button if it's useless (unless you enjoy getting more customers service requests:>
> 
> 
> Additional info:
> SQLiteFlow uses [StoreKit 2](https://developer.apple.com/storekit/) to invalidate in-app purchases, when the app launches ,if the StoreKit framework report an invalidate in-app purchase error to the app, then the Purchase Plan dialog will popup (probably displaying with no purchases), and when the Purchase Plan dialog displaying, the app will call the StoreKit to refresh the in-app purchase state (maybe this is why you after relaunching the app, everything goes right).
> 
> And I still have no clue yet that why sometime when you launch the app, the StoreKit framework report an invalidate error to the app, this should happen very rare. And What's your Mac device type? What's your macOS version? What's SQLiteFlow version?
MacBook Air M2 2022
Sonoma 14.4.1
SQLiteFlow 6.4.0

**Comment by SQLiteFlow** [comment] 2024-08-21 13:21
> From a UX perspective, I'd hide the button if it's useless

Yeah, you probably right.

> I right-click on the SQLite.db and "Open with" using SQLiteFlow. That's when I get the popup. When I click out of the popup, your software works as expected.

You mean when you launch SQLiteFlow, the Purchase Plan popup (with Lifetime License purchased displaying) and the app's main window display together, you need to close the popup (by clicking the close window button) to clean up windows to continue to work with SQLiteFlow, and that's the problem you met?

**Comment by Founderstowne** [comment] 2024-08-21 13:28
> > From a UX perspective, I'd hide the button if it's useless
> 
> Yeah, you probably right.
> 
> > I right-click on the SQLite.db and "Open with" using SQLiteFlow. That's when I get the popup. When I click out of the popup, your software works as expected.
> 
> You mean when you launch SQLiteFlow, the Purchase Plan popup (with Lifetime License purchased displaying) and the app's main window display together, you need to close the popup (by clicking the close window button) to clean up windows to continue to work with SQLiteFlow, and that's the problem you met?

Exactly.

**Comment by SQLiteFlow** [comment] 2024-08-21 13:45
@Founderstowne 
I was thinking when you launch the app, the app tells you that no purchases found and you can't use the app, since you were mentioning restoring purchases is not working.
Anyway, maybe you could try to upgrade your macOS to the latest version (macOS Sonoma 14.6.1) to see if this issue persists?

**Comment by Founderstowne** [comment] 2024-08-22 11:33
When I upgraded to the latest version of SQLiteFlow, the popup seems to have gone away.

**Comment by SQLiteFlow** [comment] 2024-08-22 11:41
@Founderstowne 
I don't change the relate logic in months, so unless you upgrade SQLiteFlow from a version released months ago, I don't think that relevant.

Since the problem disappear for now at your side, I will close this issue. If you experience this issue again, you're welcome to create a new issue to let me know about it.

**Closed as completed** 2024-08-22 11:41 UTC
